from enum import Enum


class PatternPieces(Enum):
    YELLOWFLOWERINBLUE = 1
    BLUEGEARINPINK = 2

    BLUESTARINYELLOW = 3
    YELLOWSTARINPURPLE = 4
    PURPLESTARINORANGE = 5

    BLUECROSSINORANGE = 6
    YELLOWCROSSINPINK = 7
    BLUECROSSINPURPLE = 8
    ORANGECROSSINGREEN = 9
    PINKCROSSINGREEN = 10
    PINKCROSSINLIGHTBLUE = 11
    ORANGECROSSINBLUE = 12

    BLUECIRCLEINGREEN = 13

    ORANGESQUAREINRED = 14
    YELLOWSQUAREINPINK = 15
    GREENSQUAREINYELLOW = 16
    LIGHTBLUESQUAREINBLUE = 17
    PINKSQUAREINBLUE = 18
    BLUESQUAREINYELLOW = 19

    GREENROUNDCROSSINPURPLE = 20
    PINKROUNDCROSSINBLUE = 21
    YELLOWROUNDCROSSINPURPLE = 22

    EDGE = 23