from piece import Piece
from patternpieces import PatternPieces

class PiecesBank:
    def __init__(self):
        self.pieceslist = self.createPieces()

    def createPieces(self):
        pieceslist = list()
        pieceslist.append(Piece(1, up=PatternPieces.BLUECROSSINORANGE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(2, up=PatternPieces.BLUECROSSINORANGE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(3, up=PatternPieces.YELLOWFLOWERINBLUE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(4, up=PatternPieces.BLUEGEARINPINK, right=PatternPieces.YELLOWFLOWERINBLUE))

        pieceslist.append(Piece(5, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(6, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(7, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(8, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(9, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(10, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(11, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(12, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(13, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(14, left=PatternPieces.BLUECROSSINORANGE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(15, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(16, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(17, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(18, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(19, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(20, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(21, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(22, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(23, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(24, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(25, left=PatternPieces.YELLOWFLOWERINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(26, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(27, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(28, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(29, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(30, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(31, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(32, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(33, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(34, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(35, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(36, left=PatternPieces.BLUEGEARINPINK, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(37, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(38, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(39, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(40, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(41, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(42, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(43, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(44, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(45, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(46, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(47, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(48, left=PatternPieces.BLUECIRCLEINGREEN, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(49, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(50, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(51, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(52, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(53, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(54, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.BLUECIRCLEINGREEN))
        pieceslist.append(Piece(55, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(56, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUEGEARINPINK))
        pieceslist.append(Piece(57, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.BLUECROSSINORANGE))
        pieceslist.append(Piece(58, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.ORANGESQUAREINRED))
        pieceslist.append(Piece(59, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.YELLOWFLOWERINBLUE))
        pieceslist.append(Piece(60, left=PatternPieces.ORANGESQUAREINRED, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.BLUEGEARINPINK))

        pieceslist.append(Piece(61, left=PatternPieces.YELLOWCROSSINPINK, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.BLUESTARINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(62, left=PatternPieces.YELLOWCROSSINPINK, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(63, left=PatternPieces.BLUECROSSINPURPLE, up=PatternPieces.BLUECROSSINPURPLE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(64, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(65, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(66, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.PINKCROSSINGREEN, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(67, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.BLUECROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(68, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(69, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(70, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(71, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(72, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.BLUESTARINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(73, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(74, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(75, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(76, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(77, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(78, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(79, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(80, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(81, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.BLUESTARINYELLOW, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(82, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.BLUESTARINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(83, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(84, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(85, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.PINKCROSSINGREEN, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(86, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(87, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(88, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(89, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(90, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(91, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(92, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(93, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(94, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(95, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PINKCROSSINGREEN, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(96, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(97, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(98, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(99, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(100, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWCROSSINPINK))
        pieceslist.append(Piece(101, left=PatternPieces.BLUECROSSINPURPLE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(102, left=PatternPieces.BLUECROSSINPURPLE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(103, left=PatternPieces.BLUECROSSINPURPLE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(104, left=PatternPieces.BLUECROSSINPURPLE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(105, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(106, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(107, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(108, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(109, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(110, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(111, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(112, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(113, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(114, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(115, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(116, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(117, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(118, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(119, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(120, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(121, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(122, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(123, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(124, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(125, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(126, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(127, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(128, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(129, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(130, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(131, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(132, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PINKCROSSINGREEN, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(133, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(134, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(135, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(136, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.BLUECROSSINPURPLE))
        pieceslist.append(Piece(137, left=PatternPieces.BLUESTARINYELLOW, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(138, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(139, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(140, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(141, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(142, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(143, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(144, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(145, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(146, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(147, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.BLUESTARINYELLOW, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(148, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.PINKCROSSINGREEN, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(149, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(150, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(151, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(152, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(153, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(154, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(155, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(156, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(157, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(158, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(159, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.YELLOWROUNDCROSSINPURPLE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(160, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(161, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.YELLOWROUNDCROSSINPURPLE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(162, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(163, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(164, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.BLUESTARINYELLOW))
        pieceslist.append(Piece(165, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(166, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(167, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(168, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(169, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(170, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(171, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(172, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(173, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(174, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(175, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(176, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(177, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(178, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(179, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(180, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(181, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWROUNDCROSSINPURPLE))
        pieceslist.append(Piece(182, left=PatternPieces.YELLOWROUNDCROSSINPURPLE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(183, left=PatternPieces.PINKCROSSINGREEN, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.ORANGECROSSINBLUE))
        pieceslist.append(Piece(184, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(185, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(186, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(187, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(188, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.PINKCROSSINGREEN, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(189, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(190, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(191, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(192, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(193, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(194, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.ORANGECROSSINGREEN, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(195, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(196, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(197, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(198, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(199, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(200, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(201, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(202, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(203, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(204, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(205, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.GREENROUNDCROSSINPURPLE, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(206, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.PINKCROSSINGREEN))
        pieceslist.append(Piece(207, left=PatternPieces.GREENROUNDCROSSINPURPLE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(208, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(209, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(210, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.YELLOWSTARINPURPLE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(211, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(212, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(213, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(214, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.GREENROUNDCROSSINPURPLE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(215, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(216, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(217, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(218, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(219, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(220, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.ORANGECROSSINGREEN, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(221, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(222, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.GREENROUNDCROSSINPURPLE))
        pieceslist.append(Piece(223, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(224, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.PINKSQUAREINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(225, left=PatternPieces.ORANGECROSSINGREEN, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(226, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(227, left=PatternPieces.PINKSQUAREINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(228, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(229, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(230, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(231, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(232, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.ORANGECROSSINGREEN))
        pieceslist.append(Piece(233, left=PatternPieces.YELLOWSTARINPURPLE, up=PatternPieces.YELLOWSTARINPURPLE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(234, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(235, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(236, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(237, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(238, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(239, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(240, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.GREENSQUAREINYELLOW, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(241, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.PINKSQUAREINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(242, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.YELLOWSTARINPURPLE))
        pieceslist.append(Piece(243, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.GREENSQUAREINYELLOW, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.PINKSQUAREINBLUE))
        pieceslist.append(Piece(244, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.PURPLESTARINORANGE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKSQUAREINBLUE))
        pieceslist.append(Piece(245, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.PINKSQUAREINBLUE))
        pieceslist.append(Piece(246, left=PatternPieces.YELLOWSQUAREINPINK, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.PINKSQUAREINBLUE))
        pieceslist.append(Piece(247, left=PatternPieces.GREENSQUAREINYELLOW, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.GREENSQUAREINYELLOW))
        pieceslist.append(Piece(248, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.BLUESQUAREINYELLOW, right=PatternPieces.PINKCROSSINLIGHTBLUE, down=PatternPieces.GREENSQUAREINYELLOW))
        pieceslist.append(Piece(249, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.PINKCROSSINLIGHTBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.GREENSQUAREINYELLOW))
        pieceslist.append(Piece(250, left=PatternPieces.PURPLESTARINORANGE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.YELLOWSQUAREINPINK, down=PatternPieces.GREENSQUAREINYELLOW))
        pieceslist.append(Piece(251, left=PatternPieces.PINKCROSSINLIGHTBLUE, up=PatternPieces.PINKROUNDCROSSINBLUE, right=PatternPieces.ORANGECROSSINBLUE, down=PatternPieces.PINKCROSSINLIGHTBLUE))
        pieceslist.append(Piece(252, left=PatternPieces.BLUESQUAREINYELLOW, up=PatternPieces.ORANGECROSSINBLUE, right=PatternPieces.BLUESQUAREINYELLOW, down=PatternPieces.PINKCROSSINLIGHTBLUE))
        pieceslist.append(Piece(253, left=PatternPieces.ORANGECROSSINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PURPLESTARINORANGE, down=PatternPieces.BLUESQUAREINYELLOW))
        pieceslist.append(Piece(254, left=PatternPieces.LIGHTBLUESQUAREINBLUE, up=PatternPieces.YELLOWCROSSINPINK, right=PatternPieces.LIGHTBLUESQUAREINBLUE, down=PatternPieces.PURPLESTARINORANGE))
        pieceslist.append(Piece(255, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.LIGHTBLUESQUAREINBLUE, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.PURPLESTARINORANGE))
        pieceslist.append(Piece(256, left=PatternPieces.PINKROUNDCROSSINBLUE, up=PatternPieces.YELLOWSQUAREINPINK, right=PatternPieces.PINKROUNDCROSSINBLUE, down=PatternPieces.ORANGECROSSINBLUE))

        return pieceslist

    def defineImgPath(self):
        pass